### ISSUE TITLE
Addition request

### ISSUE THREAD

**Issue by robert-little** [GuelphOntologyTeam/Backend#1]
Could you guys make the: /pet/pets endpoint also return the breed? 

Also stretch goal, could we have a picture of the cat that could also be returned in this and the /pet/view/{petID} query results? 

Thanks guys!

**Comment by Azouel4Me** [comment]
Thanks for the catch on that. It has now been added in both the get of pets and individual pets. As for images we will steer away from that for now as that would be a "feature" and we are still trying to get some basic functionality in the Backend for some people. But we will keep it in mind.
